# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'DYZB' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DYZB

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'

end
