# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’

target 'DYZB' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DYZB

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'Alamofire', '~> 4.0.1'
pod 'Kingfisher', '~> 3.1.1'

end
